/*
 * SwordfishSettingsDialog.java
 *
 * Created on Oct 6, 2008, 7:45:02 AM
 */
package swordfish.view;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;
import java.io.File;


/**
 * Currently not in use due to auto-connect.  Should be modified to change options
 * like buyIn, name, seat and the other configureable things for the player request
 * to the server
 * @author joshdavidson
 */
public class SwordfishSettingsDialog extends javax.swing.JDialog {

    private SwordfishView view;
    private static final String XML_HEADER = "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>";
    
    /** Creates new form SwordfishSettingsDialog */
    public SwordfishSettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(okButton);
    }

    public SwordfishSettingsDialog(java.awt.Frame parent, SwordfishView view, boolean modal) {
        super(parent, modal);
        this.view = view;
        initComponents();
        loadSettings();
        disableSettings();
        getRootPane().setDefaultButton(okButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stackButtonGroup = new javax.swing.ButtonGroup();
        nameTextField = new javax.swing.JTextField();
        seatComboBox = new javax.swing.JComboBox();
        logPathTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        seatLabel = new javax.swing.JLabel();
        logPathLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(swordfish.view.SwordfishApp.class).getContext().getResourceMap(SwordfishSettingsDialog.class);
        nameTextField.setText(resourceMap.getString("nameTextField.text")); // NOI18N
        nameTextField.setName("nameTextField"); // NOI18N

        seatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seat 0", "Seat 1" }));
        seatComboBox.setName("seatComboBox"); // NOI18N

        logPathTextField.setText(resourceMap.getString("logPathTextField.text")); // NOI18N
        logPathTextField.setName("logPathTextField"); // NOI18N

        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N

        seatLabel.setText(resourceMap.getString("seatLabel.text")); // NOI18N
        seatLabel.setName("seatLabel"); // NOI18N

        logPathLabel.setText(resourceMap.getString("logPathLabel.text")); // NOI18N
        logPathLabel.setName("logPathLabel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(swordfish.view.SwordfishApp.class).getContext().getActionMap(SwordfishSettingsDialog.class, this);
        okButton.setAction(actionMap.get("ok")); // NOI18N
        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N

        cancelButton.setAction(actionMap.get("cancel")); // NOI18N
        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(logPathLabel)
                            .add(nameLabel)
                            .add(seatLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(seatComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(logPathTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(89, 89, 89)
                        .add(okButton)
                        .add(18, 18, 18)
                        .add(cancelButton)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameLabel)
                    .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(seatLabel)
                    .add(seatComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(logPathLabel)
                    .add(logPathTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SwordfishSettingsDialog dialog = new SwordfishSettingsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void cancel() {
        setVisible(false);
    }

    @Action
    public void ok() {
        saveSettings();
        this.setVisible(false);
    }

    private void saveSettings() {
        try {
            savePlayerSettings();
            saveGameSettings();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this.getParent(), "Could not save settings file.", "Warning", JOptionPane.WARNING_MESSAGE);
            view.logWarning(ex.toString());
        }
    }

    private void savePlayerSettings() throws FileNotFoundException {
        view.setName(nameTextField.getText());
        view.setSeatPref(seatComboBox.getSelectedIndex());
        view.setLogPath(logPathTextField.getText());
        File playerSettings = new File("settings/playerSettings.xml");
        PrintWriter xmlPrintWriter = new PrintWriter(playerSettings);
        xmlPrintWriter.println(XML_HEADER);
        xmlPrintWriter.println("<Settings>");
        xmlPrintWriter.println("<PlayerSettings>");
        xmlPrintWriter.println("<PlayerName>" + nameTextField.getText() + "</PlayerName>");
        xmlPrintWriter.println("<PlayerSeat>" + seatComboBox.getSelectedIndex() + "</PlayerSeat>");
        xmlPrintWriter.println("<LogPath>" + logPathTextField.getText() + "</LogPath>");
        xmlPrintWriter.println("</PlayerSettings>");
        xmlPrintWriter.println("</Settings>");
        xmlPrintWriter.close();
    }

    private void saveGameSettings() throws FileNotFoundException {
        File playerSettings = new File("settings/gameSettings.xml");
        PrintWriter xmlPrintWriter = new PrintWriter(playerSettings);
        xmlPrintWriter.println(XML_HEADER);
        xmlPrintWriter.println("<Settings>");
        xmlPrintWriter.println("<GameSettings>");
        xmlPrintWriter.println("</GameSettings>");
        xmlPrintWriter.println("</Settings>");
        xmlPrintWriter.close();
    }
    
    private void loadSettings() {
        nameTextField.setText(view.getName());
        seatComboBox.setSelectedIndex(view.getSeatPref());
        logPathTextField.setText(view.getLogPath());
        
    }

    private void disableSettings() {
        seatComboBox.setEnabled(false);
        logPathTextField.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel logPathLabel;
    private javax.swing.JTextField logPathTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox seatComboBox;
    private javax.swing.JLabel seatLabel;
    private javax.swing.ButtonGroup stackButtonGroup;
    // End of variables declaration//GEN-END:variables
}
